### ISSUE TITLE
Lockdown ALTER TABLE SET ACCESS METHOD columnstore

### ISSUE THREAD

**Issue by ktny** [Mooncake-Labs/pg_mooncake#27]
### What feature are you requesting?

I want to change an existing PostgreSQL table to a columnstore table.

```sql
create table t1 (id int, name text);
insert into t1 values (1, 'Alice'), (2, 'Bob');
alter table t1 set access method columnstore;

ERROR:  columnstore_slot_callbacks not implemented
```

### Why are you requesting this feature?

If I insert the data from an existing PostgreSQL table into the newly created columnstore table, I can achieve what I want, but it takes time.

**Comment by dpxcc** [comment]
Thanks for the bug report!
We won't support `ALTER TABLE` from rowstore to columnstore
The expected workflow is to use `CTAS`: https://github.com/Mooncake-Labs/pg_mooncake/issues/26
We should provide a clearer error message in this case
