### ISSUE TITLE
build failure: missing member when initializing TableAmRoutine duckdb_methods

### ISSUE THREAD

**Issue by bpint** [Mooncake-Labs/pg_mooncake#34]
### What happens?

i built pg_mooncake from source with postgresql 16.4 (rhel patched version) headers, and got,

```log
src/pgduckdb/pgduckdb_table_am.cpp:464: sorry, unimplemented: non-trivial designated initializers not supported
```

### To Reproduce

after some investigation, i found there is a relation_toast_am member in TableAmRoutine structure for my postgresql headers. When I patched the git source with,

```diff
diff --git a/src/pgduckdb/pgduckdb_table_am.cpp b/src/pgduckdb/pgduckdb_table_am.cpp
index c857f7f..6c94cac 100644
--- a/src/pgduckdb/pgduckdb_table_am.cpp
+++ b/src/pgduckdb/pgduckdb_table_am.cpp
@@ -453,6 +453,7 @@ static const TableAmRoutine duckdb_methods = {.type = T_TableAmRoutine,
 
                                               .relation_size = duckdb_relation_size,
                                               .relation_needs_toast_table = duckdb_relation_needs_toast_table,
+                                              .relation_toast_am = NULL,
                                               /* can be null because relation_needs_toast_table returns false */
                                               .relation_fetch_toast_slice = NULL,
```

the source can be successfully built.

### OS:

RHEL 8

### pg_mooncake Version:

f1818d436328fef51c5fa418eb3b43d21ac128cd

### Postgres Version:

16.4

### Are you using pg_mooncake Docker, Neon, or the extension standalone?

pg_mooncake extension standalone

**Comment by dpxcc** [comment]
Thanks for the bug report!
We've filed a bug report and PR upstream
