### ISSUE TITLE
Support Cloudflare R2 bucket in addition to S3

### ISSUE THREAD

**Issue by nicksrandall** [Mooncake-Labs/pg_mooncake#5]
Is it possible to use a cloudflare r2 bucket instead of s3? Cloudflare's buckets have a s3 compatible API.

**Comment by paurora17** [comment]
Thank you for trying pg_mooncake! We'll add this to our roadmap. Keep you posted when ready.

**Comment by nicosuave** [comment]
Beat me to it ha. I found [this](https://github.com/Mooncake-Labs/pg_mooncake/blob/8dd7e0c88ca8d9becba34b1c1e9dcaff8c87e8ba/src/pgduckdb/pgduckdb_duckdb.cpp#L138) yesterday and was optimistic.

**Comment by dpxcc** [comment]
Should be fixed by https://github.com/Mooncake-Labs/pg_mooncake/pull/11

**Comment by nicosuave** [comment]
Any idea how often Neon updates their extensions? @nikitabase

**Comment by dpxcc** [comment]
We plan to kick off a Neon update tomorrow
