### ISSUE TITLE
Getting error when inserting data to bucket with `-` in the name

### ISSUE THREAD

**Issue by nicksrandall** [Mooncake-Labs/pg_mooncake#6]
I tried to insert into a table with a bucket with name `company-id-mooncake` and it failed with an error. When I tried with a bucket without a `-` it worked fine.

**Comment by paurora17** [comment]
Is there any other difference other than the dash (like region?)  In our testing we were using a bucket with a - with no issues. 

We'll look more into this.

**Comment by arslnb** [comment]
Try it on Neon. It will throw an error for the bucket name.

**Comment by paurora17** [comment]
I just tested this on Neon and was able to create a table. Will follow up on Slack.

**Comment by paurora17** [comment]
I tried it with `company-id-mooncake` bucket name and it ran:
![CleanShot 2024-11-04 at 12 38 20](https://github.com/user-attachments/assets/c2f72237-0c3f-4ab9-8ea8-d828caa640b5)

Did you `SET mooncake.enable_local_cache = false;`?

**Comment by nicksrandall** [comment]
I think it actually has to do with the name used when creating the secret and using a dash in that name.

**Comment by paurora17** [comment]
got it. I was able to reproduce this.
Thank you for flagging. We're on it. Will push a change ~this week. Will keep you posted when live on Neon.

**Comment by dpxcc** [comment]
Should be fixed by https://github.com/Mooncake-Labs/pg_mooncake/pull/11
